In [2]:
from autograd import grad
import autograd.numpy as np
#Some short examples of Boosting/ResNets

In [45]:
z = np.random.random((3,3))
f = lambda x: x + 2
g = lambda x: x - 4



np.sum(list(map(lambda x:x(z),[f,g])),0)

array([[-0.57438557, -1.19315059, -0.45606054],
       [-0.04128226, -0.01706088, -1.09902013],
       [-0.77801023, -1.98974185, -1.17323549]])

In [99]:
MSE(F,batch,labels)

-1.7985608910904567

In [103]:
def MeanLearners(params,x):
    return np.sum(list(map(lambda p:p*x,params)),0)

def MSE(params,x,labels):
    return -np.mean((MeanLearners(params,x)-labels)**2)



F = [1.0]#start at zero
for i in range(10):
    batch = np.random.standard_normal((10,3))
    labels = np.random.random((1,3)) 
    y = MeanLearners(F,batch)
    dL = grad(MSE)
    r = dL(F,batch,labels)
    F.append(r[0])
    print(r[0])

-1.77498302368
1
0.846276947379
2
-0.154570270213
3
0.0016380345736
4
0.279381013682
5
-0.570218463546
6
0.42948962492
7
-0.0374986136537
8
-0.0749335638711
9
-0.16966369274
10


In [10]:
act_fn = lambda x: 1/(1+np.exp(-x))
depth = 10
class 

def layer(z,w,b):
    return z + act_fn(np.dot(w,z) + b)

def Net(x):
    output = x
    for i in range(depth):
        w,b = params[i]
        output = layer(output,w,b)

def Loss(w,ims,labels):
    return np.mean(np.sum(-labels * np.log(Net(ims)),1)) #cross entropy
    
dL = grad(Loss)

#hmm. this is kida a pain in the ass for a resnet.

SyntaxError: invalid syntax (<ipython-input-10-b3f8b3611fcc>, line 3)

### Recursion
this seems similar to boosting? (recusrively) adding on an extra (residual) learner?

Could/should I be using map or reduce some how??

In [3]:
def Unroll(F,x,mapping):
    if len(F) == 1:
        return mapping(F[0],x)
    else:
        return Unroll(F[1:],mapping(F[0],x),mapping)

#special cases
linear_map = lambda f,x: f(x) #feedforward net
skip_map = lambda f,x: x + f(x) #resnet
#mul_map = lambda f,x: x * f(x)  ???
#??? = lambda f,g,x,s: f(x) + g(s) ??? a RNN?
# ??? = lambda f,x: ???? - #boosting

In [4]:
#A simple NN function to play with
class Net():
    def __init__(self,size):
        self.weights = np.random.standard_normal(size)
        self.biases = np.zeros((size[1],1))
    def __call__(self,x):
        return np.tanh(np.dot(self.weights,x) + self.biases)

In [5]:
#A feedforward net
F = [Net((3,3)) for i in range(3)] #a list of layers of a resnet
x = np.random.standard_normal((3,3))
print(Unroll(F,x,linear_map))

[[-0.32033308 -0.64245582 -0.87077009]
 [ 0.49880584  0.59990098  0.89431131]
 [-0.56066326 -0.51825348 -0.85027064]]


In [6]:
#A ResNet
F = [Net((3,3)) for i in range(3)] #a list of layers of a resnet
x = np.random.standard_normal((3,3))
print(Unroll(F,x,skip_map))

[[-1.17381352  3.0150872   1.1394695 ]
 [-2.66984591  1.39562755  1.57520143]
 [-0.66600796 -0.86168618 -3.22562506]]


In [7]:
#A RNN
N = Net((3,3)) #define a 
F = [N for t in range(10)]

#what about a multilayer RNN??
#we are passing information in two directions now.
#across in time and down in depth.

## Boosting -> ResNet

Interpret/write a ResNet in the boosting language.

Let F be a ResNet, $F:X\rightarrow Y$. With;
* depth D, with $0<i<D-1$.
* $y =  x_0 + \sum F_i(x_i)$

### SGD interpretation

http://papers.nips.cc/paper/1766-boosting-algorithms-as-gradient-descent.pdf

```python
Res = ResNet()
#for each iteration, epochs, time, .. whatever.
for t in range(T):
    y = Res.run(data)
    
    ### Calulate the residual of the function.
    # Instead, do this for each layer/weak learner
    # Backprop loss through the net to the output of layer i
    residual = grad(loss(y, label)) # a vector of partials, dLoss/dLayer_i 
    
    ### Fit the residual loss to a new function.
    # Instead, 
    h = residual
    
    ### Compute a multiplier for the new weak learner.
    # Instead set it to be a constant
    g = learning_rate
    
    ### Update our function - F = F + g h
    # SGD.
    Res.params = Res.params +  g*h
```

##### Boosting - Definitions

$$
\vec{r}^{t} = - \left[ \frac{\partial \mathcal{L} (\vec{y},F(\vec{x}_t))}{\partial F(\vec{x}_t)} \right]_{F(\vec{x}) = F(\vec{x})_{t-1}}
$$
So $\vec{r}^{t}$ is a vector of residual errors (over the dataset) for a given function F(x).
##### ResNet - Definitions
$$
\vec{r}^{t} = - \left[ \frac{\partial \mathcal{L} (\vec{y},F(\vec{x}_t))}{\partial f_i(\vec{x}_t)} \right]_{F(\vec{x}) = F(\vec{x})_{t-1}}
$$
So $\vec{r}^{t}$ is a vector of residual error (over each layer) for a given batch.

### Initialisation interpretation

```python
Res = ResNet()
#for each iteration, epochs, time, .. whatever.
for t in range(T):
    y = 
    
    ### Calulate the residual of the function.
    # Instead, do this for each layer/weak learner
    # Backprop loss through the net to the output of layer i
    residual = grad(loss(y, label)) # a vector of partials, dLoss/dLayer_i 
    
    ### Fit the residual loss to a new function.
    # Instead, initialise a new function with the parameters of the last
    h = ResNet(params = Res.params)
    for layer in layers:
        h = fit(Res.params, residual)
    
    ### Update our function -- F = F + g h
    # Instead, discard the previous function
    Res.params = h
```



### ResNet -> Boosting

```python

for batch in batches:
    

```